language: nix

before_install:
  - ./.travis/configure-nix.sh
  - ./.travis/install-new-nix.sh
  - ./.travis/install-cachix.sh

# Force VM instead of container, so that sandbox works
sudo: required

env:
  - NIX_PATH=nixpkgs=channel:nixos-unstable
  - NIX_PATH=nixpkgs=channel:nixos-18.03
  - NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/master.tar.gz

# Full clone
git:
  depth: false

script:
  - env NIX_PATH=$NIX_PATH ./.travis/build.sh --arg nixpkgs '<nixpkgs>'
